import { Injectable } from '@angular/core';
import { ReportPayload } from '../models/report-payload.model';
import {
  ReportDocumentInput,
  buildReportDocument,
  provenanceLine,
  reportDocumentTitle,
} from './report-document';

/** The formats a chat report can be taken away in. */
export type ChatReportExportFormat = 'pdf' | 'html' | 'excel';

/**
 * Exports one Chat Reports reply.
 *
 * ## Why the exports live here and not in the AI Analyst's `ExportService`
 *
 * The two features have opposite contracts. The AI Analyst computes every figure
 * from the dataset, so its document footer can say "every figure computed from
 * Dynamics 365 — not generated by AI". On this screen the MODEL authored the
 * figures. Reusing that builder would put a false claim on the artefact most
 * likely to be forwarded to someone who never saw the screen — so this one
 * carries its own provenance line instead, in the masthead and the footer.
 *
 * ## Why PDF has no library
 *
 * PDF is the HTML document sent to `window.print()`. The browser's own print
 * engine paginates, embeds fonts and honours `@page`, and does it without adding
 * megabytes to a dashboard. It also means the two formats cannot drift.
 *
 * ## Why Excel is a lazy import
 *
 * `xlsx` is ~430 kB. Loading it on the chance someone exports would cost every
 * visitor to the screen; `await import` moves it to the click. The AI Analyst's
 * `ExportService` does the same, and they share the one lazy chunk.
 */
@Injectable({ providedIn: 'root' })
export class ChatReportExportService {
  /** Whether there is anything worth exporting. Prose alone is not a report. */
  canExport(payload: ReportPayload): boolean {
    return payload.components.length > 0;
  }

  export(format: ChatReportExportFormat, input: ReportDocumentInput): void {
    switch (format) {
      case 'pdf':
        this.exportPdf(input);
        break;
      case 'html':
        this.exportHtml(input);
        break;
      case 'excel':
        void this.exportExcel(input);
        break;
    }
  }

  /** The designed document, sent to the print dialog (→ "Save as PDF"). */
  private exportPdf(input: ReportDocumentInput): void {
    const win = window.open('', '_blank', 'width=980,height=1200');
    // A blocked popup is the common case here, and failing silently would look
    // like the button is broken.
    if (!win) {
      this.exportHtml(input);
      return;
    }
    win.document.write(buildReportDocument(input));
    win.document.close();
    win.focus();
    // Give the SVG and web fonts a beat to lay out; printing too early prints a
    // half-rendered first page.
    win.setTimeout(() => win.print(), 400);
  }

  /** The same document, saved as a standalone `.html` file. */
  private exportHtml(input: ReportDocumentInput): void {
    const blob = new Blob([buildReportDocument(input)], { type: 'text/html;charset=utf-8' });
    this.download(blob, `${this.slug(reportDocumentTitle(input))}.html`);
  }

  /**
   * The report's data as a workbook.
   *
   * One sheet per component that carries figures, plus a Summary sheet that
   * opens with the provenance line — the same caveat the document shows. A
   * spreadsheet is the format most likely to be treated as raw truth, so it is
   * the one that most needs to say where the numbers came from.
   */
  private async exportExcel(input: ReportDocumentInput): Promise<void> {
    const XLSX = await import('xlsx');
    const { payload, sourceLabel, groundedRows } = input;

    const workbook = XLSX.utils.book_new();
    const used = new Set<string>();

    const summary: Record<string, unknown>[] = [
      { Field: 'Question', Value: input.question },
      { Field: 'Source', Value: sourceLabel },
      { Field: 'Exported', Value: new Date().toISOString().slice(0, 10) },
      { Field: 'Provenance', Value: provenanceLine(groundedRows) },
    ];
    if (payload.text_response) {
      summary.push({ Field: 'Commentary', Value: payload.text_response });
    }

    // A designed document has prose, layout and SVG, and no rows — there is
    // nothing to put in a cell. Said on the sheet rather than left as an
    // unexplained near-empty workbook, and it names the export that does carry
    // the report.
    if (payload.components.some((component) => component.type === 'html_document')) {
      summary.push({
        Field: 'Note',
        Value:
          'This answer is a designed report, not a table — there are no rows to export. ' +
          'Use the PDF or HTML export to keep the report itself.',
      });
    }

    // KPI tiles belong on the summary sheet: they are the headline reading of
    // the same answer, not a dataset of their own.
    for (const component of payload.components) {
      if (component.type !== 'kpi_grid') continue;
      for (const item of component.items) {
        summary.push({
          Field: item.label,
          Value: item.value,
          ...(item.change ? { Change: item.change } : {}),
        });
      }
    }
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(summary), this.sheet('Summary', used));

    for (const component of payload.components) {
      if (component.type === 'table') {
        if (!component.headers.length || !component.rows.length) continue;
        const rows = component.rows.map((row) =>
          Object.fromEntries(component.headers.map((h, i) => [h, row[i] ?? ''])),
        );
        XLSX.utils.book_append_sheet(
          workbook,
          XLSX.utils.json_to_sheet(rows),
          this.sheet(component.title || 'Table', used),
        );
        continue;
      }

      if (component.type === 'chart') {
        if (!component.labels.length || !component.datasets.length) continue;
        // A chart's underlying numbers, one column per series — which is what
        // someone opening the workbook actually wants to re-plot or check.
        const rows = component.labels.map((label, i) => {
          const row: Record<string, unknown> = { Category: label };
          for (const dataset of component.datasets) row[dataset.label] = dataset.data[i] ?? null;
          return row;
        });
        XLSX.utils.book_append_sheet(
          workbook,
          XLSX.utils.json_to_sheet(rows),
          this.sheet(component.title || 'Chart', used),
        );
      }
    }

    XLSX.writeFile(workbook, `${this.slug(reportDocumentTitle(input))}.xlsx`);
  }

  // ── Internals ────────────────────────────────────────────────────────────

  /**
   * A legal, unused sheet name.
   *
   * Excel caps names at 31 characters, forbids ``[]:*?/\``, and refuses a
   * workbook with two sheets of the same name outright. Every one of those is
   * reachable here because the titles are written by a model. Truncating alone
   * is not enough: two long titles sharing a prefix collide after the cut.
   */
  private sheet(title: string, used: Set<string>): string {
    const base = (title || 'Sheet').replace(/[[\]:*?/\\]/g, ' ').trim().slice(0, 31) || 'Sheet';
    let name = base;
    for (let i = 2; used.has(name); i++) name = `${base.slice(0, 28)} ${i}`;
    used.add(name);
    return name;
  }

  private download(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  private slug(title: string): string {
    return (
      (title || 'report')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 60) || 'report'
    );
  }
}
