import { GeneratedReportArtifact } from '../models/report-artifact.model';

/**
 * Wraps a generated fragment into the complete, standalone HTML document.
 *
 * ## One document, three destinations
 *
 * This function is the single source of truth the brief calls for:
 *
 *     GeneratedReportArtifact.html
 *              │
 *     buildArtifactDocument()
 *              ├── iframe srcdoc   (the preview)
 *              ├── .html download  (Export HTML)
 *              └── print job       (Export PDF)
 *
 * All three are the SAME string. There is no second renderer, so the preview
 * cannot flatter a PDF that comes out differently, and a fix to the print rules
 * cannot land in one and miss the other.
 *
 * ## Why the wrapper exists at all
 *
 * The model is asked for a body-level fragment, not a page, for three reasons.
 * The charset has to be right or a currency symbol renders as mojibake. The
 * content-security policy below must be OURS, not something the model can choose
 * to omit. And the provenance footer must be present on every copy, including the
 * one someone forwards to a colleague who never saw the screen — which is exactly
 * the copy most likely to be mistaken for a system-generated report.
 *
 * ## The content-security policy is load-bearing
 *
 * `sandbox` with no `allow-scripts` stops script. It does NOT stop a `<img
 * src="https://…">`, which loads happily from an opaque origin and is a working
 * exfiltration channel: the request URL can carry anything the document knows.
 * `default-src 'none'` closes that. The allowances are the minimum a designed,
 * self-contained report needs:
 *
 *   style-src 'unsafe-inline'  the report's own <style> block and style="" attrs
 *   img-src data:              a data: URI, never a URL
 *   font-src data:             the same for an embedded face
 *   form-action / base-uri     'none' — nothing to submit to, nothing to rebase
 *
 * Note it also applies to the EXPORTED file, where there is no iframe at all. A
 * saved report is a document someone will open directly, and it should be no more
 * capable there than it was on screen.
 */

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * The policy, as one line.
 *
 * `frame-ancestors`, `report-uri` and `sandbox` are deliberately absent — they
 * are ignored in a `<meta>` CSP and only produce a console warning, which would
 * teach a future reader that the whole header is being ignored.
 */
const CSP = [
  "default-src 'none'",
  "style-src 'unsafe-inline'",
  'img-src data:',
  'font-src data:',
  'media-src data:',
  "form-action 'none'",
  "base-uri 'none'",
].join('; ');

/**
 * The wrapper's own styles. Deliberately almost nothing.
 *
 * The report brings its own design and anything opinionated here would fight it.
 * What is left is the three things a document cannot sensibly be without: a white
 * ground (it is printed), media that cannot overflow its container, and
 * `border-box`, which every piece of modern CSS is written against and which the
 * report's own rules can still override.
 *
 * The print block belongs here rather than in the fragment because it is about
 * the PAGE, not the report: margins, and not letting the browser inflate type on
 * paper. Page-break behaviour inside the report is the report's own job, and the
 * design brief asks for it.
 */
const RESET = [
  '*,*::before,*::after{box-sizing:border-box}',
  'html,body{margin:0;padding:0;background:#ffffff;color:#111827;',
  '-webkit-text-size-adjust:100%;text-size-adjust:100%}',
  'body{font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}',
  'img,svg,video{max-width:100%}',
  '@page{size:A4;margin:14mm}',
  '@media print{html,body{background:#fff}body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}',
].join('');

/**
 * The provenance line, appended to every copy of the document.
 *
 * ## Why this is not optional
 *
 * On the AI Analyst and the Report Builder the app computes every figure, so
 * their exported documents can honestly say "not generated by AI". Here the model
 * wrote the figures as well as the layout. They are GROUNDED — the only numbers
 * it was given are real aggregates computed against Dynamics 365, and the prompt
 * forbids inventing any other — but nothing downstream recomputes them.
 *
 * That distinction is invisible in a beautifully designed document, which is
 * precisely why it is stated on the document rather than only on the screen. The
 * exported file is the copy that gets forwarded; deleting this line would make it
 * indistinguishable from a verified report.
 */
function provenance(artifact: GeneratedReportArtifact): string {
  const { moduleLabel, generatedAt, provider, slice } = artifact.metadata;

  const when = new Date(generatedAt);
  const stamp = Number.isNaN(when.getTime()) ? '' : when.toLocaleString();

  const facts = [
    `Module: ${moduleLabel}`,
    slice ? `Filtered to ${slice}` : 'Whole module — no filter applied',
    stamp ? `Generated ${stamp}` : '',
    provider ? `Model: ${provider}` : '',
  ].filter(Boolean);

  return [
    '<footer class="rl-provenance">',
    `<p class="rl-provenance-facts">${escapeHtml(facts.join(' · '))}</p>`,
    '<p class="rl-provenance-note">',
    'This report’s layout <strong>and its figures</strong> were written by an AI model from ',
    'aggregates computed against Dynamics 365. The figures are grounded in those aggregates — ',
    'the model was given no other numbers — but they are not recomputed by the application. ',
    'Check anything you are about to act on.',
    '</p>',
    '</footer>',
  ].join('');
}

/** Styles for the footer above. Prefixed so they cannot collide with the report. */
const PROVENANCE_CSS = [
  '.rl-provenance{max-width:1100px;margin:48px auto 0;padding:16px 24px 32px;',
  'border-top:1px solid #e5e7eb;font:12px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",',
  'Roboto,Helvetica,Arial,sans-serif;color:#6b7280;break-inside:avoid}',
  '.rl-provenance p{margin:0 0 6px}',
  '.rl-provenance-facts{font-weight:600;color:#4b5563}',
  '.rl-provenance strong{color:#4b5563}',
].join('');

/**
 * The complete document, ready for an iframe, a file or a printer.
 *
 * `lang` and `dir` are fixed to English/LTR: every module in this app reports in
 * English, and the Executive Arabic report is a different feature with its own
 * renderer. If a right-to-left module ever lands here, this is the one place to
 * change.
 */
export function buildArtifactDocument(artifact: GeneratedReportArtifact): string {
  return [
    '<!doctype html>',
    '<html lang="en" dir="ltr">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<meta http-equiv="Content-Security-Policy" content="${CSP}">`,
    `<title>${escapeHtml(artifact.title)}</title>`,
    artifact.summary ? `<meta name="description" content="${escapeHtml(artifact.summary)}">` : '',
    `<style>${RESET}${PROVENANCE_CSS}</style>`,
    '</head>',
    '<body>',
    artifact.html,
    provenance(artifact),
    '</body>',
    '</html>',
  ]
    .filter(Boolean)
    .join('\n');
}

/**
 * A filesystem-safe name for the exported file, derived from the report's title.
 *
 * The title is model output, so it is reduced to letters, digits and hyphens
 * rather than trusted — a download name is one of the few places a string from
 * outside reaches an OS API.
 */
export function artifactFilename(artifact: GeneratedReportArtifact, extension: string): string {
  const slug =
    artifact.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'report';

  return `${slug}-${artifact.metadata.generatedAt.slice(0, 10)}.${extension}`;
}
